# ================================================================== #
# ------------------------- SECTION CONFIG PUBLIC ------------------ #
# ================================================================== #
#
# Place the address where the site is hosted, and the base
# of website. If there is no base, leave blank.
#
site_url: "http://williamcanin.com" # the base hostname & protocol for your site
site_baseurl: "/chameleon-jek/" # the subpath of your site, e.g. /blog/
 # description: used by search engines
description: >
  Chameleon Jek - Blog &'Portfolio for Jekyll

# Meta tag for Expires / Cache Control - Max 1 Year
expires: "Sat, 24 Dec 2016 00:10:00 GMT"
cache_control: "max-age=120" # Default: public
# Meta tag for Expires / Cache Control - Max 1 Year


# Language support (english / portuguese )
language: "english"
# Language support

#
#==========================================================



# Block - Theme specific configuration [BEGIN]
theme:
  # language: "portuguese" #support: (english / portuguese)
  title: "Chameleon Jek"
  subtitle_site: "Blog & Portfolio for Jekyll"
  navbar_collapse_icon: "nav-icon-white.svg"


  # ========= Begin Config Effects =============
  # Navbar Fixed (yes/no)
  navbar_fixed: "yes"
  # Shake Site title
  shake_title_navbar: "yes"
  # Shake menu navbar
  shake_menus_navbar: "yes"
  # Effects FadeIn (yes/no)
  fadeIn: "yes"
  # Shake title posts
  shake_title_posts: "yes"
 # ========= End Effects =============


# Block - FakeLoader
# fakeLoader (yes/no)
  fakeLoader: "no"
  fl_local: "all" # { all }
  fl_timeToHide: "1500" # milliseconds, default 1500
  # Default fl_bgColor: #2D4F25
  fl_bgColor: "#2D4F25"
  fl_spinner: "spinner4" # Default, spinner4
  fl_spinnerColor: "#fff"
  fl_hideNav: "yes" # Default yes
  # fl_textSpinner: "Please wait, loading page..." # construction
# Block - FakeLoader


# Block Avatar Image
  avatar: "out.png"
  avatar_mouse_hover: "over.png"
# Block Avatar Image



# Block - Shares posts config
  post_sharing: "yes" #(yes/no)
# Block - Shares posts config



# Block - Posts Author
  # Image
  author_image: "william.png"
  # String
  str_post_by_title: "Post by:"
  # str_name_author_post: "Chameleon Jek"
  author_post_description: >
    <p>In this field you describe a summary about you and what you do.
      This Jekyll theme is created by
        <a href="http://github.com/williamcanin" target="_blank">
          William C. Canin
        </a>
    </p>
# Block - Posts Author




# Block - Footer / Copyrights
  footer_text:
    str_text1: "Chameleon Jek - Blog & Portfolio for Jekyll"
    str_text2: "Theme made with: "
    maintence1_link_by: "http://jekyllrb.com"
    maintence2_link_by: "http://getbootstrap.com/"
    maintence1_text_by: "Jekyll"
    maintence2_text_by: "Twitter Bootstrap"
    str_text3: "Theme made by: "
    design_layout_link_by: "http://github.com/williamcanin"
    design_layout_text_by: "William Canin"
    copyright_initial_year:  "Copyright 2015"
# Block - Footer / Copyrights



# Block - Socialize Icons Navbar
  rss: "chameleon-jek" #Your FeedBurner feed. Ex. williamcanin
  email_address: "your_email@gmail.com"
  behance:
  bitbucket:
  dribbble:
  disqus: "your_user_disqus"
  facebook: "your_user_facebook"
  flickr:
  github: "your_user_github"
  google_plus: "your_user_google+"
  instagram:
  lastfm:
  linkedin:  "your_url_complete_linkedin"
  myspace:
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "http://stackoverflow.com/users/123456/your_user_stack_exchange"
  steam:
  skype:
  tumblr:
  twitter:
  vivaolinux: "" # Exemple: ~your_username
  wordpress:
  youtube: "your_user_canal"
# Block - Socialize Icons Navbar


# Block - Project posts
# Their projects '_posts/portfolio' will be for customers?
  client_yesno: "yes"
# Block - Project posts


# Block - Scripts Google Abalytics
  google_analytics: "UA-XXXXXX-0X" # tracking id, e.g. "UA-000000-01"
# Block - Scripts Google Abalytics


# Block - Google AdSense
  Include_AdSense: "no" #[ yes | no ]
  Style: "display:block"
  Ad_Client: "ca-pub-XXXXXXXXXXXXXXXXXX"
  Ad_Slot: "XXXXXXXXXX" #ID
  Ad_Format: "auto"
# Block - Google AdSense




# Block - Comments for Disqus
  disqus_shortname: "williamcanin" # Your User of Disqus. ex: "william"
# Block - Comments for Disqus



# Block - Adorned Header in Index

  adorned_header_enable: "yes" # ( yes | no )
  adorned_header_type: "text" # ( img | text )
  adorned_header_img: "page-heading-banner.png"
  adorned_header_text: >
    <p>
      Hello, I am the theme Chameleon Jek
    </p>
    <p>
      Welcome to the home page.
    </p>
#Block - Adorned Header in Index



# Block - Localization strings
  str_comments: >
    <p>
      Comments
    </p>
    <p>
      Leave your comment
    </p>
  str_comments_portfolio: >
    <p>
      Comments
    </p>
    <p>
      Leave your comment in portfolio
    </p>
  str_follow_on: "Follow on"
  str_modal_feed_title: "Follow RSS/Feed of"
  str_form_feed_input: "Enter your email address"
  str_form_feed_submit: "Subscribe"
  str_feed_reader: "Subscribe in a reader"
  str_continue_reading: "Continue reading"
  str_total_pages: "Pages: "
  str_placeholder_search: "Search in "
  str_no_search_results: "Oh Gosh! No results found"
  str_title_result_search: "Results:"
  str_icon_comment_post: "Comment"
  str_shares_title: "<p>Share this post in</p>"
  str_article: "Article"
  str_nocomment: "Comment disabled"
  str_edit_this_post: "Edit this post"
  # Block - Localization strings

# Block - Theme specific configuration [END]



# Block directory of posts
# Description > This directory will be the directory where the posts to your GitHub
#               This variable is for the button "Edit this post" of each post.
# Important! Do not use the trailing slash
#
  directory_posts_github: "https://github.com/williamcanin/chameleon-jek/tree/master/_posts/blog"
# Block directory of posts


# Block - Email of Gravatar for avatar to your site.
# Add your email gravatar. Exemple: "william.costa.canin@gmail.com"
# To insert the MD5, use: $rake gravatar:md5 - $rake help
email_gravatar: "william.costa.canin@gmail.com"
# Block - Email of Gravatar for avatar to your site.









# ================================================================== #
# ------------------------- SECTION CONFIG PRIVATE ----------------- #
# ================================================================== #
#
#
# Block - Includes files and folder build jekyll
include: ['_pages']
# Block - Includes files and folder build jekyll


# Block - Build settings
url: "http://0.0.0.0:4000"
baseurl: ""
# Permalink Default: /:categories/:year/:month/:day/:title/
# Permalink optional: /:title/
permalink: /:title/
destination: ./_site
# Block - Build settings


# Block - MD5 EMail of Gravatar.
gravatar_md5:
# Block - MD5 EMail of Gravatar.


# Block - Markdown
# highlighter: pygments
# highlighter: true
markdown: kramdown # { kramdown | redcarpet }
kramdown:
  extensions: [
    "no_intra_emphasis",
    "fenced_code_blocks",
    "autolink",
    "tables",
    "strikethrough",
    "superscript",
    "with_toc_data"
  ]
# Block - Markdown





# Block - Excludes files and folder build jekyll
exclude: [
# Animate Css
'assets/vendor/animate.css/source',
'assets/vendor/animate.css/*.js',
'assets/vendor/animate.css/*.json',
# Bootstrap
'assets/vendor/bootstrap/fonts',
'assets/vendor/bootstrap/grunt',
'assets/vendor/bootstrap/less',
'assets/vendor/bootstrap/js',
'assets/vendor/bootstrap/Gruntfile.js',
'assets/vendor/bootstrap/*.json',
'assets/vendor/bootstrap/*.md',
'assets/vendor/bootstrap/package.js',
# Bootstrap Drawer
'assets/vendor/bootstrap-drawer/docs',
'assets/vendor/bootstrap-drawer/example',
'assets/vendor/bootstrap-drawer/js',
'assets/vendor/bootstrap-drawer/less',
'assets/vendor/bootstrap-drawer/gulpfile.js',
'assets/vendor/bootstrap-drawer/*.json',
'assets/vendor/bootstrap-drawer/*.md',
'assets/vendor/bootstrap-drawer/*.html',
# Font Awesome
'assets/vendor/font-awesome-custom/less',
'assets/vendor/font-awesome-custom/scss',
'assets/vendor/font-awesome-custom/*.html',
'assets/vendor/font-awesome-custom/*.js',
'assets/vendor/font-awesome-custom/*.map',
'assets/vendor/font-awesome-custom/*.json',
# Fonts Raleway
'assets/vendor/fonts-raleway/less',
'assets/vendor/fonts-raleway/scss',
'assets/vendor/fonts-raleway/dev',
'assets/vendor/fonts-raleway/*.html',
'assets/vendor/fonts-raleway/*.js',
'assets/vendor/fonts-raleway/*.map',
'assets/vendor/fonts-raleway/*.json',
'assets/vendor/fonts-raleway/*.md',
# JQuery
'assets/vendor/jquery/src',
'assets/vendor/jquery/bower.json',
'assets/vendor/jquery/*.txt',
# JQuery Easing
'assets/vendor/jquery.easing/*.json',
'assets/vendor/jquery.easing/*.md',
# Modernizr
'assets/vendor/modernizr/**/*',
'assets/vendor/modernizr/grunt.js',
'assets/vendor/modernizr/*.md',
'!assets/vendor/modernizr/modernizr.js',
# Simple Jekyll Search
'assets/vendor/simple-jekyll-search/*.json',
'assets/vendor/simple-jekyll-search/*.md',

# Defaults
'/**/*/LICENSE',
'Gruntfile.js',
'Gulpfile.js',
'package.json',
'bower.json',
'README.md',
'Gemfile',
'Rakefile',
'node_modules',
'src',
'_gist_cache',
'assets/images/preview',
'README-PtBr.md',
'**/*/.zip',
'**/*/.log',
'nohup.out',
'**/*/.lock',
'./.bundle',
'AUTHORS',
'docs',
'CREDITS',
'gh-pages',
'CHANGELOG.md',
'COPYING',
'administration'
]
# Block - Excludes files and folder build jekyll